# Generated by Django 4.2.2 on 2023-06-30 04:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TurfBookingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateField(default=datetime.datetime(2023, 6, 30, 10, 23, 45, 633683), max_length=50)),
                ('feedback_message', models.CharField(max_length=500)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TurfBookingApp.customer')),
            ],
        ),
    ]
