# Generated by Django 4.2.3 on 2023-07-07 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TurfBookingApp', '0003_contact_alter_feedback_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 16, 48, 38, 196491), max_length=50),
        ),
    ]
