version: '3'

services:
  web:
    build: .
    command: gunicorn TurfBooking.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=turf_db
      - DB_USER=root
      - DB_PASSWORD=malhar
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=turf_db
      - MYSQL_ROOT_PASSWORD=malhar
